# Example of a CLAGE ISX with slave ID 97 connected
# to a Modbus RTU to Modbus TCP gateway 192.168.5.160
modbus:
  name: modbus_hub
  type: tcp
  host: 192.168.5.160
  port: 502
  delay: 2
  message_wait_milliseconds: 30
  retries: 3
  timeout: 5
  climates:
    - name: clage_isx_setpoint_temp
      slave: 97
      input_type: holding
      address: 0
      target_temp_register: 0
      data_type: uint16
      scan_interval: 2
      offset: 0
      precision: 1
      scale: 0.1
      temp_step: 0.5
      max_temp: 60
      min_temp: 20
      temperature_unit: C
  sensors:
    - name: clage_isx_intake_temp
      slave: 97
      input_type: input
      address: 0
      data_type: uint16
      device_class: temperature
      scan_interval: 10
      offset: 0
      precision: 1
      scale: 0.1
      max_value: 80
      min_value: 0
      unit_of_measurement: °C
    - name: clage_isx_outtake_temp
      slave: 97
      input_type: input
      address: 1
      data_type: uint16
      device_class: temperature
      scan_interval: 10
      offset: 0
      precision: 1
      scale: 0.1
      max_value: 80
      min_value: 0
      unit_of_measurement: °C
    - name: clage_water_flow
      slave: 97
      input_type: input
      address: 2
      data_type: uint16
#      device_class: None
      scan_interval: 2
      offset: 0
      precision: 1
      scale: 0.1
      max_value: 12
      min_value: 0
      unit_of_measurement: l/min
    - name: clage_power_comsumption
      slave: 97
      input_type: input
      address: 3
      data_type: uint16
      device_class: power
      scan_interval: 2
      offset: 0
      precision: 1
      scale: 0.1
      max_value: 27
      min_value: 0
      unit_of_measurement: kW
